# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nJJpiha5NBOzxJ_0r1ZSudhxjJWODsvn
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.decomposition import PCA

data = pd.read_csv('cleaned_data.csv')
x = data.drop('diagnosis', axis=1)
y = data['diagnosis']

print("Dataset shape:", x.shape)
print("Target classes:", y.unique())

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

model = SVC(kernel='rbf', C=2, gamma='scale')
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassfication Report:\n", classification_report(y_test, y_pred))
print("\nAccuracy:", accuracy_score(y_test, y_pred))

pca = PCA(n_components=2)
x_pca = pca.fit_transform(x)

x_train_pca, x_test_pca, y_train_pca, y_test_pca = train_test_split(x_pca, y, test_size=0.3, random_state=42)
model_pca = SVC(kernel='rbf', C=2, gamma='scale')
model_pca.fit(x_train_pca, y_train_pca)

x_min, x_max = x_pca[:,0].min()-1, x_pca[:,0].max()+1
y_min, y_max = x_pca[:,1].min()-1, x_pca[:,1].max()+1
xx, yy = np.meshgrid(np.linspace(x_min, x_max, 200),
                     np.linspace(y_min, y_max, 200))
z = model_pca.predict(np.c_[xx.ravel(), yy.ravel()])
z = z.reshape(xx.shape)

plt.figure(figsize=(8,6))
plt.contourf(xx, yy, z, alpha=0.3, cmap=plt.cm.coolwarm)
sns.scatterplot(x=x_pca[:,0], y=x_pca[:,1], hue=y,
                palette="coolwarm", edgecolor="k", s=60)
plt.title("SVM Classification (Breast Cancer Dataset with PCA)")
plt.xlabel("PCA Feature 1")
plt.ylabel("PCA Feature 2")
plt.show()

input_data = (12.05,14.63,78.04,449.3,0.1031,0.09092,0.06592,0.02749,0.1675,0.06043,0.2636,0.7294,1.848,19.87,0.005488,0.01427,0.02322,0.00566,0.01428,0.002422,13.76,20.7,89.88,582.6,0.1494,0.2156,0.305,0.06548,0.2747,0.08301)

# change the input data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)
#reshape the numpy array as we are predicting for the datapoint
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)
print(prediction)

if(prediction[0] == 1):
    print('The Breast Cancer is Malignant')
else:
    print('The Breast Cancer is Benign')